version: 1.0.{build}
image: Visual Studio 2017
skip_branch_with_pr: true

environment:
  nodejs_version: "8"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@6 -g
  - npm ci --silent
  - node --version
  - npm --version
  - choco install googlechrome --limit-output --ignore-checksum

build: off

test_script:
  - npm run lint
  - npm test -- --progress=false
  - appveyor-retry npm run e2e
  - npm run build -- --progress=false

#on_finish:
 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
